### ISSUE TITLE
Add Users

### ISSUE THREAD

**Issue by declan727** [cockroach/webisoder#1]
Sorry to bother you however I am at a loss on how to add a user. when I click on "signup" it redirects me to /# but this page looks just like the main page. I have tried to add a user directly to the sqlite database but this also did not work. I do not know what I am missing. Any help would be appreciated.

**Comment by cockroach** [comment]
Sorry for the long delay. Webisoder is still very much unfinished, I only just implemented the ability for users to sign up (i.e. this issue should now be resolved). 

Feel free to poke around and try it out but don't expect it to do anything useful yet. Still, thanks for reporting this, I'm looking forward to getting more bug reports.
